import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: Request) {
  try {
    const data = await request.json();
    console.log('API Route: Received form data:', data);
    const { email, _subject, _autoresponder, ...remainingData } = data;

    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
      console.warn('API Route Warning: SMTP credentials missing in environment variables. Simulating success for local development.');
      return NextResponse.json({ success: true, message: 'Local Dev Mode: Emails simulated successfully' });
    }

    // Create a transporter using SMTP
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: process.env.SMTP_PORT === '465', // true for 465, false for other ports
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
      tls: {
        rejectUnauthorized: false
      }
    });

    // Format data into a nice table for the admin
    const tableRows = Object.entries(remainingData)
      .map(([key, value]) => {
        const label = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
        const displayValue = typeof value === 'object' ? JSON.stringify(value) : String(value);
        return `
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold; width: 30%; color: #666;">${label}</td>
            <td style="padding: 10px; border-bottom: 1px solid #eee; color: #333;">${displayValue}</td>
          </tr>
        `;
      })
      .join('');

    // 1. Send Email to Admin (yogagarhi@gmail.com)
    const adminMailOptions = {
      from: `"YogaGarhi Website" <${process.env.SMTP_USER}>`,
      to: 'yogagarhi@gmail.com',
      subject: _subject || 'New Website Submission',
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 10px; overflow: hidden;">
          <div style="background-color: #6366f1; color: white; padding: 20px; text-align: center;">
            <h2 style="margin: 0;">New Form Submission</h2>
          </div>
          <div style="padding: 20px;">
            <p style="margin-bottom: 20px;">You have received a new submission from your website.</p>
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold; width: 30%; color: #666;">User Email</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee; color: #333;">${email || 'N/A'}</td>
              </tr>
              ${tableRows}
            </table>
            <div style="margin-top: 30px; padding-top: 20px; border-top: 2px solid #f0f0f0; text-align: center; color: #999; font-size: 12px;">
              Generated by YogaGarhi Website System
            </div>
          </div>
        </div>
      `,
    };

    // 2. Send Auto-responder to User
    const userMailOptions = email ? {
      from: `"YogaGarhi" <${process.env.SMTP_USER}>`,
      to: email,
      subject: _subject ? `Confirmation: ${_subject}` : 'We Have Received Your Request YogaGarhi Bali',
      text: _autoresponder || `Namaste,

Thank you for reaching out to YogaGarhi.

Your message has been received. A member of our team will connect with you personally within 24 hours.

At YogaGarhi, yoga is approached as a living tradition rooted in discipline, awareness, and direct experience. Whether your inquiry is about learning, teaching, deepening your practice, or simply understanding the path ahead, we believe clarity unfolds best through conscious conversation, not urgency.

Until we connect, we invite you to pause for a moment, soften the breath, and allow this step to settle naturally.

We look forward to connecting with you.

With respect and sincerity,
YogaGarhi Team – Bali
Authentic Yoga • Rooted in Tradition • Lived with Awareness`,
      html: _autoresponder ? `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 10px; overflow: hidden; padding: 20px;">
          <h2 style="color: #6366f1;">Namaste</h2>
          <div style="white-space: pre-wrap; line-height: 1.6; color: #333;">${_autoresponder}</div>
          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; font-size: 14px; color: #666;">
            <strong>YogaGarhi Team - Bali</strong><br>
            Authentic Yoga &bull; Rooted in Tradition
          </div>
        </div>
      ` : `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
          </head>
          <body style="margin: 0; padding: 0; background-color: #f9f9f9; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">
            <div style="padding: 40px 10px;">
              <div style="max-width: 600px; margin: 0 auto; padding: 40px; color: #333; line-height: 1.8; border: 1px solid #f0f0f0; border-radius: 12px; background-color: #ffffff; box-shadow: 0 4px 15px rgba(0,0,0,0.05);">
                <div style="text-align: center; margin-bottom: 30px;">
                  <h1 style="color: #6366f1; font-weight: 300; margin: 0; font-size: 28px; letter-spacing: 2px;">Namaste</h1>
                  <div style="width: 40px; height: 1px; background-color: #6366f1; margin: 15px auto;"></div>
                </div>
                
                <p style="font-size: 16px; margin-bottom: 20px;">Thank you for reaching out to <strong>YogaGarhi</strong>.</p>
                
                <p style="font-size: 16px; margin-bottom: 20px;">Your message has been received. A member of our team will connect with you personally within 24 hours.</p>
                
                <p style="font-size: 16px; color: #555; margin-bottom: 20px; font-style: italic;">"At YogaGarhi, yoga is approached as a living tradition rooted in discipline, awareness, and direct experience. Whether your inquiry is about learning, teaching, deepening your practice, or simply understanding the path ahead, we believe clarity unfolds best through conscious conversation, not urgency."</p>
                
                <p style="font-size: 16px; color: #555; margin-bottom: 20px;">Until we connect, we invite you to pause for a moment, soften the breath, and allow this step to settle naturally.</p>
                
                <p style="font-size: 16px; margin-bottom: 30px;">We look forward to connecting with you.</p>
                
                <div style="margin-top: 40px; border-top: 1px solid #eee; padding-top: 25px;">
                  <p style="margin-bottom: 5px; color: #666; font-size: 15px;">With respect and sincerity,</p>
                  <p style="margin-top: 0; font-weight: bold; font-size: 18px; color: #333; margin-bottom: 10px;">YogaGarhi Team – Bali</p>
                  <div style="font-size: 13px; color: #888; border-left: 2px solid #6366f1; padding-left: 12px; margin-top: 15px;">
                    <strong>Authentic Yoga • Rooted in Tradition • Lived with Awareness</strong>
                  </div>
                </div>
              </div>
            </div>
          </body>
        </html>
      `,
    } : null;

    // Send both emails
    console.log('API Route: Attempting to send admin email...');
    await transporter.sendMail(adminMailOptions);
    console.log('API Route: Admin email sent successfully.');

    if (userMailOptions) {
      console.log('API Route: Attempting to send user auto-responder...');
      await transporter.sendMail(userMailOptions);
      console.log('API Route: User auto-responder sent successfully.');
    }

    return NextResponse.json({ success: true, message: 'Emails sent successfully' });
  } catch (error: any) {
    console.error('Nodemailer Error:', error);
    return NextResponse.json(
      { success: false, message: 'Failed to send emails', error: error.message },
      { status: 500 }
    );
  }
}
