import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

// Helper to escape HTML characters to prevent XSS / injection in HTML emails
function escapeHtml(value: unknown): string {
  if (value === null || value === undefined) return '';
  const str = typeof value === 'object' ? JSON.stringify(value) : String(value);
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export async function POST(request: Request) {
  try {
    const data = await request.json();
    console.log('API Route (/api/send-email): Received form data:', data);
    const { email, _subject, _autoresponder, ...remainingData } = data;

    // Check for SMTP configuration
    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
      console.error('API Route Error: SMTP credentials missing in environment variables.');
      return NextResponse.json(
        { success: false, message: 'SMTP credentials missing.' },
        { status: 500 }
      );
    }

    // Create a transporter using SMTP
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT || '465'),
      secure: process.env.SMTP_PORT === '465' || !process.env.SMTP_PORT, // true for port 465
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
      tls: {
        rejectUnauthorized: false,
      },
    });

    // Format remaining form fields into a sanitized, styled HTML table for the admin
    const tableRows = Object.entries(remainingData)
      .map(([key, value]) => {
        const label = escapeHtml(key.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase()));
        const displayValue = escapeHtml(value);
        return `
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold; width: 32%; color: #555;">${label}</td>
            <td style="padding: 10px; border-bottom: 1px solid #eee; color: #222;">${displayValue}</td>
          </tr>
        `;
      })
      .join('');

    const sanitizedSubject = escapeHtml(_subject || 'New Website Submission');

    // 1. Send Notification Email to Admin (yogagarhi@gmail.com)
    const adminMailOptions = {
      from: `"YogaGarhi Website" <${process.env.SMTP_USER}>`,
      to: 'yogagarhi@gmail.com',
      replyTo: email || 'yogagarhi@gmail.com',
      subject: _subject || 'New Website Submission',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 10px; overflow: hidden; background-color: #ffffff;">
          <div style="background-color: #0b3b2c; color: white; padding: 20px; text-align: center;">
            <h2 style="margin: 0; font-size: 20px; color: #f5b942;">YogaGarhi &bull; Website Submission</h2>
            <p style="margin: 6px 0 0; color: #d4ebe2; font-size: 14px;">${sanitizedSubject}</p>
          </div>
          <div style="padding: 24px;">
            <p style="margin-top: 0; margin-bottom: 18px; color: #333; font-size: 15px;">You have received a new inquiry/submission from the website:</p>
            <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold; width: 32%; color: #555;">User Email</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee; color: #222;">${escapeHtml(email || 'N/A')}</td>
              </tr>
              ${tableRows}
            </table>
            <div style="margin-top: 30px; padding-top: 15px; border-top: 1px solid #eee; text-align: center; color: #888; font-size: 12px;">
              Generated by YogaGarhi Website System
            </div>
          </div>
        </div>
      `,
    };

    // 2. Send Auto-responder to User (Student / Inquirer)
    const userMailOptions = email
      ? {
          from: `"YogaGarhi" <${process.env.SMTP_USER}>`,
          to: email,
          replyTo: 'yogagarhi@gmail.com',
          subject: _subject ? `Confirmation: ${_subject}` : 'We Have Received Your Request - YogaGarhi',
          text:
            _autoresponder ||
            `Namaste,

Thank you for reaching out to YogaGarhi.

Your message has been received. A member of our team will connect with you personally within 24 hours.

At YogaGarhi, yoga is approached as a living tradition rooted in discipline, awareness, and direct experience. Whether your inquiry is about learning, teaching, deepening your practice, or simply understanding the path ahead, we believe clarity unfolds best through conscious conversation, not urgency.

Until we connect, we invite you to pause for a moment, soften the breath, and allow this step to settle naturally.

We look forward to connecting with you.

With respect and sincerity,
YogaGarhi Team
Authentic Yoga • Rooted in Tradition • Lived with Awareness`,
          html: _autoresponder
            ? `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #16533f; border-radius: 12px; overflow: hidden; background-color: #ffffff; box-shadow: 0 4px 15px rgba(0,0,0,0.06);">
          <div style="background-color: #0b3b2c; color: white; padding: 24px 20px; text-align: center;">
            <p style="margin: 0 0 4px; color: #f5b942; font-size: 12px; font-weight: bold; letter-spacing: 1.5px; text-transform: uppercase;">YOGAGARHI ASHRAM &bull; RISHIKESH & BALI</p>
            <h1 style="margin: 0; font-size: 22px; color: #ffffff;">Namaste</h1>
          </div>
          <div style="padding: 28px 24px; color: #2d3748; line-height: 1.7; font-size: 15px;">
            <div style="white-space: pre-wrap; color: #333;">${escapeHtml(_autoresponder)}</div>
            <div style="margin-top: 32px; padding-top: 20px; border-top: 1px solid #eee; font-size: 14px; color: #4b5563;">
              <p style="margin: 0;">With warm regards & blessings,</p>
              <p style="margin: 4px 0 0; font-weight: bold; color: #0b3b2c; font-size: 15px;">YogaGarhi Team</p>
              <p style="margin: 2px 0 0; font-size: 12px; color: #6b7280;">Authentic Yoga &bull; Rooted in Tradition &bull; Lived with Awareness</p>
            </div>
          </div>
        </div>
      `
            : `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
          </head>
          <body style="margin: 0; padding: 0; background-color: #f9f9f9; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">
            <div style="padding: 40px 10px;">
              <div style="max-width: 600px; margin: 0 auto; padding: 36px 28px; color: #333; line-height: 1.8; border: 1px solid #16533f; border-radius: 12px; background-color: #ffffff; box-shadow: 0 4px 15px rgba(0,0,0,0.05);">
                <div style="text-align: center; margin-bottom: 25px;">
                  <p style="margin: 0 0 6px; color: #b45309; font-size: 12px; font-weight: bold; letter-spacing: 1.5px; text-transform: uppercase;">YOGAGARHI ASHRAM</p>
                  <h1 style="color: #0b3b2c; font-weight: 300; margin: 0; font-size: 26px; letter-spacing: 2px;">Namaste</h1>
                  <div style="width: 40px; height: 2px; background-color: #f5b942; margin: 12px auto;"></div>
                </div>
                
                <p style="font-size: 15px; margin-bottom: 18px;">Thank you for reaching out to <strong>YogaGarhi</strong>.</p>
                
                <p style="font-size: 15px; margin-bottom: 18px;">Your message has been received. A member of our team will connect with you personally within 24 hours.</p>
                
                <p style="font-size: 14px; color: #555; margin-bottom: 18px; font-style: italic; background-color: #f7faf8; padding: 12px 16px; border-left: 3px solid #0b3b2c; border-radius: 4px;">"At YogaGarhi, yoga is approached as a living tradition rooted in discipline, awareness, and direct experience. Whether your inquiry is about learning, teaching, deepening your practice, or simply understanding the path ahead, we believe clarity unfolds best through conscious conversation, not urgency."</p>
                
                <p style="font-size: 15px; color: #555; margin-bottom: 18px;">Until we connect, we invite you to pause for a moment, soften the breath, and allow this step to settle naturally.</p>
                
                <p style="font-size: 15px; margin-bottom: 24px;">We look forward to connecting with you.</p>
                
                <div style="margin-top: 30px; border-top: 1px solid #eee; padding-top: 20px;">
                  <p style="margin-bottom: 4px; color: #666; font-size: 14px;">With respect and sincerity,</p>
                  <p style="margin-top: 0; font-weight: bold; font-size: 16px; color: #0b3b2c; margin-bottom: 4px;">YogaGarhi Team</p>
                  <div style="font-size: 12px; color: #888; margin-top: 6px;">
                    Authentic Yoga &bull; Rooted in Tradition &bull; Lived with Awareness
                  </div>
                </div>
              </div>
            </div>
          </body>
        </html>
      `,
        }
      : null;

    // Send emails
    console.log('API Route (/api/send-email): Attempting to send admin email...');
    await transporter.sendMail(adminMailOptions);
    console.log('API Route (/api/send-email): Admin email sent successfully.');

    if (userMailOptions) {
      console.log('API Route (/api/send-email): Attempting to send user auto-responder to:', email);
      await transporter.sendMail(userMailOptions);
      console.log('API Route (/api/send-email): User auto-responder sent successfully.');
    }

    return NextResponse.json({ success: true, message: 'Emails sent successfully' });
  } catch (error: any) {
    console.error('API Route (/api/send-email) Error:', error);
    return NextResponse.json(
      { success: false, message: 'Failed to send emails', error: error.message },
      { status: 500 }
    );
  }
}
